# $FirebaseSDKVersion = '6.13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SummitCollegeApp' do
  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth', '~> 6.10'
  pod 'Firebase/Analytics'
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SummitCollegeAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'SummitCollegeApp-tvOS' do
  # Pods for SummitCollegeApp-tvOS

  target 'SummitCollegeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end